default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  port: 5432
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: auto_app_development

test:
  <<: *default
  database: auto_app_test

production:
  <<: *default
  database: auto_app_production